### ISSUE TITLE
Laravel 5.1?

### ISSUE THREAD

**Issue by ronnorthrip** [duxet/laravel-rethinkdb#11]
Are you working on moving this to Laravel 5.1?

**Comment by danwilliams** [comment]
I've submitted a pull request to bring in my branch that fixes it to work with Laravel 5.1. You can find the branch here for now: https://github.com/danwilliams/laravel-rethinkdb

**Comment by danwilliams** [comment]
My pull request has been approved and my fixes are now on master in the official repository. You should find it works with Laravel 5.1 for you now.

**Comment by ronnorthrip** [comment]
Thank You Dan!

**Comment by karllhughes** [comment]
Confirmed. This package works for me on Laravel 5.1 as well. Can we close this issue?

**Comment by duxet** [comment]
If there is no other compatibility issues, then yes @karllhughes :)
