### ISSUE TITLE
Can't create a migration file for Laravel 5.2 install

### ISSUE THREAD

**Issue by mtpultz** [duxet/laravel-rethinkdb#21]
I followed the installation to install this service provider, but each time I try to create a migration file I get this error:

``` bash
  [ErrorException]
  Argument 2 passed to duxet\Rethinkdb\Console\Migrations\MigrateMakeCommand::__construct() must be an instance
   of Illuminate\Foundation\Composer, instance of Illuminate\Support\Composer given, called in D:\projects\app\vendor\duxet\laravel-rethinkdb\src\RethinkdbServiceProvider.php on line 41 and defined
```

I'm on line 41 and can see that the second parameter is `$composer`, which equals `$composer = $app['composer'];`, but I'm not sure what/where `$app` comes from so I can't confirm it is using an instance of `Illuminate\Foundation\Composer`.

Anyone running into this issue?

**Comment by zaherg** [comment]
its related to the new changes which they have done in L5.2 .. am looking at it right now

**Comment by mtpultz** [comment]
Hi @linuxjuggler, it's the `Illuminate\Foundation\Composer` in MigrationMakeCommand it needs to be `Illuminate\Support\Composer`

**Comment by zaherg** [comment]
actually its not that , the error says that it should be `Illuminate\Foundation\Composer` mean while the class is getting the new class `Illuminate\Support\Composer`.

am looking at it right now, lets hope it will be fixed , but also if we fix this , it might cause an issue with anyone using L5.1.

let me try to fix it first then we can talk about it

**Comment by mtpultz** [comment]
Hi @linuxjuggler, once I changed `MigrateMakeCommand` to use `Illuminate\Support\Composer` I could migrate.  Looks like it was only changed in the ServiceProvider, which already uses `Illuminate\Support\ServiceProvider`.  As I understand it the error though it says differently is indicating that `MigrateMakeCommand` is using the wrong class.

``` php
namespace duxet\Rethinkdb\Console\Migrations;

use duxet\Rethinkdb\Migrations\MigrationCreator;
use Illuminate\Database\Console\Migrations\MigrateMakeCommand as LaravelMigration;
use Illuminate\Support\Composer; // Originally was Illuminate\Foundation\Composer

class MigrateMakeCommand extends LaravelMigration
{
```

Which is what the parent class uses as well:

``` php
<?php

namespace Illuminate\Database\Console\Migrations;

use Illuminate\Support\Composer;
use Illuminate\Database\Migrations\MigrationCreator;

class MigrateMakeCommand extends BaseCommand
{
```

**Comment by zaherg** [comment]
you can do that manually till they approve my pull request , check the changes from my pull request https://github.com/duxet/laravel-rethinkdb/commit/471c0f67ca532556017388631ab85fe4334a9e46

**Comment by zaherg** [comment]
@mtpultz you are correct and thats what I have just did, but I hope the guys will merge it in another branch lets say 5.2 cause 5.1 still use the old composer namespace

**Comment by mtpultz** [comment]
k thanks @linuxjuggler.  I agree a branch for 5.2 would be a good idea.
