### ISSUE TITLE
Support php-rql 2.2.0

### ISSUE THREAD

**Issue by etienneroudeix** [duxet/laravel-rethinkdb#23]
Hello,
Thank you for the job you've done so far.

I wonder if you plan to make laravel-rethinkdb based on php-rql 2.2.0 instead of 2.0.1 ?

I'm running an issue about \DateTime when created from a comma formatted epoch_time (due to FR_fr locale). And php-rql 2.2.0 fixed it.

Cheers

**Comment by zaherg** [comment]
@etienneroudeix have you tried to fork the package and update the `composer.json` file to use `php-rql 2.2.0` , if so did you faced any issues ? or no it was working like charm ?

**Comment by etienneroudeix** [comment]
@linuxjuggler yes I tried and met some issues : for example, class 'r\RqlDriverError' was moved to 'r\Exceptions\RqlDriverError'

**Comment by zaherg** [comment]
ok, lets hope it will be updated soon

**Comment by zaherg** [comment]
@etienneroudeix I just pushed a pull request  https://github.com/duxet/laravel-rethinkdb/pull/24 lets hope they will merge it soon

**Comment by etienneroudeix** [comment]
@linuxjuggler  :+1: great job ! thank you !
