### ISSUE TITLE
Migrations not working, Illuminate Blueprint being used in SchemaBuilder

### ISSUE THREAD

**Issue by Jickelsen** [duxet/laravel-rethinkdb#39]
When creating a migration everything corresponds to the example in the readme (the blueprint used is from use duxet\Rethinkdb\Schema\Blueprint), but when running it I get the following error.

`[Symfony\Component\Debug\Exception\FatalThrowableError]
Type error: Argument 1 passed to Chat::{closure}() must be an instance of duxet\Rethinkdb\Schema\Blueprint, instance of Illuminate\Database\Schema\Blueprint given, called in /var/www/laravel/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php on line 146`

Using Laravel 5.2.

**Comment by IlyaVorozhbit** [comment]
+1
