### ISSUE TITLE
Access level to duxet\Rethinkdb\Query\Builder::$operators must be public (as in class Illuminate\Database\Query\Builder)

### ISSUE THREAD

**Issue by SlyDave** [duxet/laravel-rethinkdb#41]
Laravel 5.4

QueryBuilder extends Illuminate's QueryBuilder but doesn't correctly implement the same scope 

````Access level to duxet\Rethinkdb\Query\Builder::$operators must be public (as in class Illuminate\Database\Query\Builder)````

**Comment by jeffaknine** [comment]
In `duxet\Rethinkdb\Query\Builder` change `protected $operators` to `public $operators`
