### ISSUE TITLE
RethinkDB\Schema\Blueprint@index should compatible with Illuminate\Schema@index

### ISSUE THREAD

**Issue by ux-engineer** [duxet/laravel-rethinkdb#44]
Just installed Laravel 5.4.25 (Laravel Spark) and and set up 'homestead' table on RethinkDB.

Changed _use duxet\Rethinkdb\Schema\Blueprint;_ to each of Spark's migration file. Ran _php artisan migrate_ and got this error:

> [ErrorException]
>   Declaration of duxet\RethinkDB\Schema\Blueprint::index($column, $options = NULL) should be compatible with Illuminate\Database\Schema\Blueprint::index($columns, $name = NULL, $algorithm = NULL)

**Comment by randuck-dev** [comment]
Just piggybacking on this. Having the same issue

**Comment by vzool** [comment]
Same problem here at Laravel 5.5.17 :(

**Comment by bhavikji** [comment]
getting the same issue have you find any hack for this?
I'm using Laravel 5.5.20

**Comment by randuck-dev** [comment]
I have not. We have since gone away from using Rethink for our project, but if someone one day finds a fix I am still interested.

**Comment by bhavikji** [comment]
issue is now fixed in latest commit pls check and close this issue :)
